Repository malaheaven/issue-tracker, pull requests merged in 2021-09, with the labels that each got.

#154 [FE] 로그아웃 기능 구현 및 변경된 API 적용
  FE/src/components/Header/Logo.tsx
  FE/src/components/Header/UserMenu.tsx
  FE/src/components/IssueWrite/WriteFooter.tsx
  FE/src/components/LabelList/LabelEdit.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/util/API.ts
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/hooks/useRefreshAPIDataState.tsx
  FE/src/util/hooks/useRefreshUserState.tsx
Labels: FE

#157 [#156] refactor: swagger 버전 2.9.2를 3.0.0으로 변경
  BE/server/build.gradle
  BE/server/src/main/java/com/team11/issue/config/SwaggerConfig.java
  BE/server/src/main/java/com/team11/issue/controller/SwaggerController.java
Labels: BE

#160 [FE] 일부 레이아웃 비활성 및 환경변수 추가
  FE/.env.development
  FE/.env.production
  FE/src/App.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Common/DefaultInput.tsx
  FE/src/components/Common/PrimaryButton.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/RegisterPage.tsx
  FE/src/pages/index.tsx
Labels: FE

#161 Ios/feature/146/draw view with networkdata
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LabelListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Controller/NewIssueViewController.swift
  iOS/issueTracker/issueTracker/Entity/Comment.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/IssueResponse.swift
  iOS/issueTracker/issueTracker/Entity/Issues.swift
  iOS/issueTracker/issueTracker/Entity/Label.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/Network/OAuth/KeyChainService.swift
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/Label.storyboard
  iOS/issueTracker/issueTracker/View/IssueDetailView.swift
  iOS/issueTracker/issueTracker/View/IssueTableViewCell.swift
  iOS/issueTracker/issueTracker/View/LabelListView.swift
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: iOS

#162 [IOS] [#147] Feat: :sparkles: 마크다운 뷰 기능 구현
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/issueTracker/Controller/NewIssueViewController.swift
  iOS/issueTracker/issueTracker/StoryBoard/NewIssue.storyboard
Labels: iOS

#166 [FE] 생성, 수정, 삭제등의 동작을 했을 시 다시 서버에 데이터를 요청하도록 변경
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueWrite/WriteFooter.tsx
  FE/src/components/LabelList/LabelEdit.tsx
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssueWritePage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/hooks/useRefreshAPIDataState.tsx
  FE/src/util/store/global.tsx
  FE/src/util/store/index.tsx
  FE/src/util/store/issueList.tsx
Labels: bug, FE

#167 [FE] Main 브랜치로 merge.
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueWrite/WriteFooter.tsx
  FE/src/components/LabelList/LabelEdit.tsx
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssueWritePage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/hooks/useRefreshAPIDataState.tsx
  FE/src/util/store/global.tsx
  FE/src/util/store/index.tsx
  FE/src/util/store/issueList.tsx
Labels: FE
