Repository malaheaven/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#16 [BE] spring project init
  BE/server/.gitignore
  BE/server/build.gradle
  BE/server/gradle/wrapper/gradle-wrapper.jar
  BE/server/gradle/wrapper/gradle-wrapper.properties
  BE/server/gradlew
  BE/server/gradlew.bat
  BE/server/settings.gradle
  BE/server/src/main/java/com/team11/issue/IssueApplication.java
  BE/server/src/main/resources/application.properties
  BE/server/src/test/java/com/team11/issue/IssueApplicationTests.java
Labels: BE

#27 [BE] mysql 연동
  BE/server/build.gradle
  BE/server/src/main/resources/application.properties
Labels: BE

#28 [BE] cors 적용
  BE/server/src/main/java/com/team11/issue/config/WebConfig.java
Labels: BE

#34 [BE] Oauth 구현
  BE/server/.gitignore
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/dto/ExceptionResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/oauth/AccessTokenDTO.java
  BE/server/src/main/java/com/team11/issue/dto/oauth/UserInfoDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginResponseDTO.java
  BE/server/src/main/java/com/team11/issue/exception/AccessTokenNotFoundException.java
  BE/server/src/main/java/com/team11/issue/exception/GlobalExceptionHandler.java
  BE/server/src/main/java/com/team11/issue/exception/OauthException.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauth.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauthConfig.java
  BE/server/src/main/java/com/team11/issue/oauth/Oauth.java
  BE/server/src/main/java/com/team11/issue/oauth/errorHandler/RestTemplateResponseErrorHandler.java
  BE/server/src/main/java/com/team11/issue/repository/UserRepository.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/resources/schema.sql
Labels: BE

#39 [BE] jwtToken 발행하기 구현
  BE/server/build.gradle
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/dto/ResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginResponseDTO.java
  BE/server/src/main/java/com/team11/issue/exception/GlobalExceptionHandler.java
  BE/server/src/main/java/com/team11/issue/repository/UserRepository.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/java/com/team11/issue/util/JwtUtil.java
  BE/server/src/main/resources/schema.sql
Labels: BE

#40 [BE] jpa 적용
  BE/server/build.gradle
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/dto/ExceptionResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/ResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/oauth/AccessTokenDTO.java
  BE/server/src/main/java/com/team11/issue/dto/oauth/UserInfoDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginResponseDTO.java
  BE/server/src/main/java/com/team11/issue/exception/OauthException.java
  BE/server/src/main/java/com/team11/issue/repository/UserRepository.java
  BE/server/src/main/java/com/team11/issue/util/JwtUtil.java
  BE/server/src/main/resources/application.properties
Labels: BE

#42 [BE] refactor Oauth
  BE/server/.gitignore
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauth.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauthConfig.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauthUtil.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/resources/application.properties
  BE/server/src/main/resources/schema.sql
Labels: BE

#43 [BE] swagger 적용
  BE/server/build.gradle
  BE/server/src/main/java/com/team11/issue/config/SwaggerConfig.java
  BE/server/src/main/java/com/team11/issue/controller/SwaggerController.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
Labels: BE

#26 [iOS] Login&issueList UI 작성
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker/Assets.xcassets/filterIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/filterIcon.imageset/filterIcon.png
  iOS/issueTracker/issueTracker/Assets.xcassets/milestoneIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/milestoneIcon.imageset/milestoneIcon.png
  iOS/issueTracker/issueTracker/Assets.xcassets/selectIcon.imageset/Contents.json
  iOS/issueTracker/issueTracker/Assets.xcassets/selectIcon.imageset/selectIcon.png
  iOS/issueTracker/issueTracker/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/ViewController.swift
  iOS/issueTracker/issueTracker/Identity/StoryBoardIdentity.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/View/IssueListTableViewCell.swift
Labels: IOS

#46 issueList&Filter구현
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker/Controller/IssueListFilterViewController.swift
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/Test.swift
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/View/HeaderView.swift
  iOS/issueTracker/issueTracker/View/filterOptionCell.swift
Labels: iOS

#50 [#48] Entity 규정
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker/Entity/Comment.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Issues.swift
  iOS/issueTracker/issueTracker/Entity/Label.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/Rooms.swift
  iOS/issueTracker/issueTracker/Entity/SendIssue.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
Labels: iOS

#53 [BE] oauth useragent header 적용
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginRequestDTO.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauth.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauthUtil.java
  BE/server/src/main/java/com/team11/issue/oauth/Oauth.java
  BE/server/src/main/java/com/team11/issue/oauth/UserAgent.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/resources/application.properties
Labels: BE

#55 [FE] 로그인, 이슈 작성, 레이블 리스트 컴포넌트 UI 작업
  FE/.prettierrc
  FE/package.json
  FE/public/image/profile.png
  FE/src/App.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Common/DefaultButton.tsx
  FE/src/components/Common/DefaultInput.tsx
  FE/src/components/Common/Icons.tsx
  FE/src/components/Common/PrimaryButton.tsx
  FE/src/components/Header/Logo.tsx
  FE/src/components/Header/UserMenu.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/NavFilter/TabBar/AddButton.tsx
  FE/src/components/IssueList/NavFilter/TabBar/Tabs.tsx
  FE/src/components/IssueList/NavFilter/TabBar/index.tsx
  FE/src/components/IssueList/NavFilter/index.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/index.css
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssueWritePage.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/RegisterPage.tsx
  FE/src/pages/index.tsx
  FE/src/util/reference.ts
  FE/src/util/styles/CommonStyledCSS.tsx
  FE/src/util/styles/GlobalStyle.tsx
  FE/src/util/styles/theme/index.ts
  FE/src/util/styles/theme/styled.d.ts
  FE/src/util/types.tsx
Labels: FE

#56 [FE] 이슈리스트 UI 작업
  FE/src/App.tsx
  FE/src/components/Common/Icons.tsx
  FE/src/components/IssueList/ListTable/ListBody.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/ListTable/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/util/reference.ts
  FE/src/util/styles/theme/index.ts
Labels: FE

#79 fix: .gitignore
  .gitignore
  .gitignore~Stashed changes
  iOS/issueTracker/.swiftlint.yml
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/Podfile.lock~Stashed changes
  iOS/issueTracker/Podfile~Stashed changes
  iOS/issueTracker/Pods/Manifest.lock
  iOS/issueTracker/Pods/Pods.xcodeproj/project.pbxproj
  iOS/issueTracker/Pods/SwiftLint/LICENSE
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-Info.plist
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-acknowledgements.markdown
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-acknowledgements.plist
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-dummy.m
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-umbrella.h
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.debug.xcconfig
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.modulemap
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.release.xcconfig
  iOS/issueTracker/Pods/Target Support Files/SwiftLint/SwiftLint.debug.xcconfig
  iOS/issueTracker/Pods/Target Support Files/SwiftLint/SwiftLint.release.xcconfig
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj~Stashed changes
  iOS/issueTracker/issueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/issueTracker/issueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTracker.xcscheme
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTrackerTests.xcscheme
  iOS/issueTracker/issueTracker.xcworkspace/contents.xcworkspacedata
  iOS/issueTracker/issueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Controller/ViewController.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/View/HeaderView.swift
  iOS/issueTracker/issueTrackerTests/Info.plist
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: iOS

#80 fix: .gitignore
  .gitignore
  .gitignore~Stashed changes
  iOS/issueTracker/.swiftlint.yml
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/Podfile.lock~Stashed changes
  iOS/issueTracker/Podfile~Stashed changes
  iOS/issueTracker/Pods/Manifest.lock
  iOS/issueTracker/Pods/Pods.xcodeproj/project.pbxproj
  iOS/issueTracker/Pods/SwiftLint/LICENSE
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-Info.plist
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-acknowledgements.markdown
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-acknowledgements.plist
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-dummy.m
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker-umbrella.h
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.debug.xcconfig
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.modulemap
  iOS/issueTracker/Pods/Target Support Files/Pods-issueTracker/Pods-issueTracker.release.xcconfig
  iOS/issueTracker/Pods/Target Support Files/SwiftLint/SwiftLint.debug.xcconfig
  iOS/issueTracker/Pods/Target Support Files/SwiftLint/SwiftLint.release.xcconfig
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj~Stashed changes
  iOS/issueTracker/issueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/issueTracker/issueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTracker.xcscheme
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTrackerTests.xcscheme
  iOS/issueTracker/issueTracker.xcworkspace/contents.xcworkspacedata
  iOS/issueTracker/issueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Controller/ViewController.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/View/HeaderView.swift
  iOS/issueTracker/issueTrackerTests/Info.plist
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: iOS

#81 [BE] oauth user logger 추가
  BE/server/src/main/java/com/team11/issue/config/SwaggerConfig.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauth.java
Labels: BE

#85 [BE] fe는 User-Agent 전부 허용으로 변경
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauth.java
  BE/server/src/main/resources/application.properties
Labels: BE

#86 [#33] feat: :sparkles: OAuth 로그인 구현 - 1
  FE/package.json
  FE/src/App.tsx
  FE/src/components/LabelList/LabelEdit.tsx
  FE/src/pages/LabelListPage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/pages/LoginPage.tsx
  FE/src/pages/index.tsx
Labels: FE

#87 [FE] 현 프로젝트에서 쓰이는 ListModal 적용 중.. - 1
  FE/package.json
  FE/src/App.tsx
  FE/src/components/Common/BackgroundFluid.tsx
  FE/src/components/Common/CircleCheckBox.tsx
  FE/src/components/Common/Icons.tsx
  FE/src/components/Common/Label.tsx
  FE/src/components/Common/ListModal.tsx
  FE/src/components/Common/Modal.tsx
  FE/src/components/Common/PrimaryButton.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/ListTable/ListBody.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/ListTable/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/NavFilter/TabBar/Tabs.tsx
  FE/src/components/IssueList/NavFilter/TabBar/index.tsx
  FE/src/components/IssueList/NavFilter/index.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/util/recoil/index.tsx
  FE/src/util/recoil/issueList.tsx
Labels: FE

#88 [#33] feat: OAuth 구현
  FE/src/pages/LoginCallBackPage.tsx
Labels: FE

#89 [BE] 도메인 개발
  BE/server/src/main/java/com/team11/issue/domain/Assignees.java
  BE/server/src/main/java/com/team11/issue/domain/Comment.java
  BE/server/src/main/java/com/team11/issue/domain/History.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/domain/IssueHasLabel.java
  BE/server/src/main/java/com/team11/issue/domain/Label.java
  BE/server/src/main/java/com/team11/issue/domain/Milestone.java
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/resources/application.properties
Labels: BE

#93 [FE] 현 프로젝트에서 쓰이는 ListModal 적용 중 (이벤트 설정) - 2
  FE/src/App.tsx
  FE/src/components/Common/BackgroundFluid.tsx
  FE/src/components/Common/ListModal.tsx
  FE/src/components/Common/Modal.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/ListTable/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/NavFilter/index.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/util/recoil/index.tsx
  FE/src/util/recoil/issueList.tsx
  FE/src/util/reference.ts
  FE/src/util/store/index.tsx
  FE/src/util/store/issueListAtoms.tsx
Labels: FE

#94 [iOS] 네트워크 테스트 함수 작성
  iOS/issueTracker/.swiftlint.yml
  iOS/issueTracker/KeyChaineServiceTests/Info.plist
  iOS/issueTracker/KeyChaineServiceTests/KeyChaineServiceTests.swift
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTracker.xcscheme
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTrackerTests.xcscheme
  iOS/issueTracker/issueTracker/Controller/IssueFilterViewController.swift
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Controller/NewIssueViewController.swift
  iOS/issueTracker/issueTracker/Controller/Test.swift
  iOS/issueTracker/issueTracker/Entity/Comment.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Issues.swift
  iOS/issueTracker/issueTracker/Entity/Label.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/SendIssue.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Entity/testEntity/test.json
  iOS/issueTracker/issueTracker/Info.plist
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/Network/OAuth/KeyChainService.swift
  iOS/issueTracker/issueTracker/Network/OAuth/OAuthManager+Extenstion.swift
  iOS/issueTracker/issueTracker/Network/OAuth/Service.swift
  iOS/issueTracker/issueTracker/SceneDelegate.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/IssueList.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/Label.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/MileStone.storyboard
  iOS/issueTracker/issueTracker/StoryBoard/MyAccount.storyboard
  iOS/issueTracker/issueTracker/View/CustomSectionHeader.swift
  iOS/issueTracker/issueTracker/View/FilterOptionCell.swift
  iOS/issueTracker/issueTracker/View/HeaderView.swift
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: iOS

#95 [iOS] 네트워크 테스트 함수 작성
  iOS/issueTracker/.swiftlint.yml
  iOS/issueTracker/KeyChaineServiceTests/Info.plist
  iOS/issueTracker/KeyChaineServiceTests/KeyChaineServiceTests.swift
  iOS/issueTracker/Podfile
  iOS/issueTracker/Podfile.lock
  iOS/issueTracker/issueTracker.xcodeproj/project.pbxproj
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTracker.xcscheme
  iOS/issueTracker/issueTracker.xcodeproj/xcshareddata/xcschemes/issueTrackerTests.xcscheme
  iOS/issueTracker/issueTracker/Controller/IssueListViewController.swift
  iOS/issueTracker/issueTracker/Controller/LoginViewController.swift
  iOS/issueTracker/issueTracker/Entity/Comment.swift
  iOS/issueTracker/issueTracker/Entity/History.swift
  iOS/issueTracker/issueTracker/Entity/Issue.swift
  iOS/issueTracker/issueTracker/Entity/IssueCount.swift
  iOS/issueTracker/issueTracker/Entity/Label.swift
  iOS/issueTracker/issueTracker/Entity/Milestone.swift
  iOS/issueTracker/issueTracker/Entity/User.swift
  iOS/issueTracker/issueTracker/Entity/testEntity/test.json
  iOS/issueTracker/issueTracker/Info.plist
  iOS/issueTracker/issueTracker/Network/EndPoint.swift
  iOS/issueTracker/issueTracker/Network/NetworkManager.swift
  iOS/issueTracker/issueTracker/Network/OAuth/KeyChainService.swift
  iOS/issueTracker/issueTracker/Network/OAuth/OAuthManager+Extenstion.swift
  iOS/issueTracker/issueTracker/Network/OAuth/Service.swift
  iOS/issueTracker/issueTracker/SceneDelegate.swift
  iOS/issueTracker/issueTracker/StoryBoard/Base.lproj/Main.storyboard
  iOS/issueTracker/issueTracker/View/FilterOptionCell.swift
  iOS/issueTracker/issueTrackerTests/issueTrackerTests.swift
Labels: iOS

#96 [BE]DTO 개발
  BE/server/src/main/java/com/team11/issue/domain/Assignees.java
  BE/server/src/main/java/com/team11/issue/domain/Comment.java
  BE/server/src/main/java/com/team11/issue/domain/History.java
  BE/server/src/main/java/com/team11/issue/domain/IssueHasLabel.java
  BE/server/src/main/java/com/team11/issue/dto/comment/CommentRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/comment/CommentResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/comment/CommentsResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/history/HistoryResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueChangeStatusRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueDetailResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssuesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/label/LabelRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/label/LabelResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/label/LabelsResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/IssueCountResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/MilestoneRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/MilestoneResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/MilestonesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/UserResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/UsersResponseDTO.java
Labels: BE

#98 [BE] jwt interceptor 적용
  BE/server/src/main/java/com/team11/issue/config/JwtAuthInterceptor.java
  BE/server/src/main/java/com/team11/issue/config/WebConfig.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/util/JwtUtil.java
Labels: BE

#99 [BE]유저 전체 목록 조회 기능 구현, swagger tag 및 설명 변경
  BE/server/src/main/java/com/team11/issue/config/WebConfig.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/dto/user/UsersResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/UserRepository.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
Labels: BE

#100 [BE] 이슈 생성하기, 라벨 생성하기, 마일스톤 생성하기
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/domain/Assignees.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/domain/IssueHasLabel.java
  BE/server/src/main/java/com/team11/issue/domain/Label.java
  BE/server/src/main/java/com/team11/issue/domain/Milestone.java
  BE/server/src/main/java/com/team11/issue/repository/AssigneeRepository.java
  BE/server/src/main/java/com/team11/issue/repository/IssueHasLabelRepository.java
  BE/server/src/main/java/com/team11/issue/repository/IssueRepository.java
  BE/server/src/main/java/com/team11/issue/repository/LabelRepository.java
  BE/server/src/main/java/com/team11/issue/repository/MilestoneRepository.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
Labels: BE

#104 [BE] refactor: interceptor을 통해 가져온 jwt token 으로 변경
  BE/server/src/main/java/com/team11/issue/config/SwaggerConfig.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
Labels: BE

#105 [BE] 이슈 생성에 대한 부분 누락된 내용 수정
  BE/server/src/main/java/com/team11/issue/domain/History.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueRequestDTO.java
  BE/server/src/main/java/com/team11/issue/repository/HistoryRepository.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#108 [BE] 코멘트 수정
  BE/server/src/main/java/com/team11/issue/controller/CommentController.java
  BE/server/src/main/java/com/team11/issue/domain/Comment.java
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
Labels: BE

#109 [BE] 코멘트 삭제
  BE/server/src/main/java/com/team11/issue/controller/CommentController.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
Labels: BE

#110 [BE] 라벨링 수정
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/domain/Label.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
Labels: BE

#111 [BE]라벨링 삭제
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
Labels: BE

#112 [BE]마일스톤 수정
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/domain/Milestone.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
Labels: BE

#113 [BE]마일스톤 삭제
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
Labels: BE

#114 [BE]라벨링 조회
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
Labels: BE

#115 [BE]라벨링 전체 조회
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/dto/label/LabelsResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/LabelRepository.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
Labels: BE

#116 [BE]마일스톤 조회
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/IssueCountResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/IssueRepository.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
Labels: BE

#117 [BE]마일스톤 전체 조회
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/MilestonesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/MilestoneRepository.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
Labels: BE

#118 [BE]이슈 상태변경
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#119 [BE] 이슈 수정
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/domain/Assignees.java
  BE/server/src/main/java/com/team11/issue/domain/History.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/repository/AssigneeRepository.java
  BE/server/src/main/java/com/team11/issue/repository/IssueHasLabelRepository.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#120 [BE]이슈 삭제
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#121 [#64] 이슈 삭제2
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#122 [#61] 이슈 조회 구현
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/domain/Assignees.java
  BE/server/src/main/java/com/team11/issue/domain/History.java
  BE/server/src/main/java/com/team11/issue/domain/User.java
  BE/server/src/main/java/com/team11/issue/dto/comment/CommentsResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueDetailResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/CommentRepository.java
  BE/server/src/main/java/com/team11/issue/repository/HistoryRepository.java
  BE/server/src/main/java/com/team11/issue/repository/IssueHasLabelRepository.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#123 [#59] 이슈 전체 조회 구현
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssuesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/repository/IssueRepository.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#128 [FE] 이슈리스트 모달 기능 적용 중 - 1
  FE/craco.config.js
  FE/package.json
  FE/src/components/Common/ListModal.tsx
  FE/src/components/Common/LoadingSpinner.tsx
  FE/src/components/Header/UserMenu.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/ListTable/ListBody.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/ListTable/index.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/NavFilter/TabBar/AddButton.tsx
  FE/src/components/IssueList/NavFilter/TabBar/Tabs.tsx
  FE/src/components/IssueList/NavFilter/TabBar/index.tsx
  FE/src/components/IssueList/NavFilter/index.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/pages/IssuePage.tsx
  FE/src/util/API.ts
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/reference.ts
  FE/src/util/store/index.tsx
  FE/src/util/store/issueList.tsx
  FE/src/util/store/issueListAtoms.tsx
  FE/src/util/types.tsx
  FE/src/util/types/api.ts
  FE/src/util/types/index.ts
  FE/src/util/types/normal.ts
  FE/src/util/util.ts
  FE/tsconfig.json
  FE/tsconfig.paths.json
Labels: FE

#132 [#131] dummy data 개발
  BE/server/src/main/java/com/team11/issue/IssueApplication.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueDetailResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueResponseDTO.java
  BE/server/src/main/java/com/team11/issue/util/JwtUtil.java
  BE/server/src/main/resources/application.properties
  BE/server/src/main/resources/data.sql
Labels: BE

#134 [BE]받지 않아도 되는 parameter hidden처리
  BE/server/src/main/java/com/team11/issue/controller/CommentController.java
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
Labels: BE

#137 [BE] 이슈 리팩토링, 줄맞춤
  BE/server/src/main/java/com/team11/issue/IssueApplication.java
  BE/server/src/main/java/com/team11/issue/config/JwtAuthInterceptor.java
  BE/server/src/main/java/com/team11/issue/config/RequestLoggingFilterConfig.java
  BE/server/src/main/java/com/team11/issue/controller/CommentController.java
  BE/server/src/main/java/com/team11/issue/controller/IssueController.java
  BE/server/src/main/java/com/team11/issue/controller/LabelController.java
  BE/server/src/main/java/com/team11/issue/controller/MilestoneController.java
  BE/server/src/main/java/com/team11/issue/controller/UserController.java
  BE/server/src/main/java/com/team11/issue/domain/Issue.java
  BE/server/src/main/java/com/team11/issue/dto/comment/CommentsResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueChangeStatusRequestDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueDetailResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssuesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/milestone/MilestonesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/LoginResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/user/UsersResponseDTO.java
  BE/server/src/main/java/com/team11/issue/oauth/GitHubOauthUtil.java
  BE/server/src/main/java/com/team11/issue/oauth/Oauth.java
  BE/server/src/main/java/com/team11/issue/oauth/UserAgent.java
  BE/server/src/main/java/com/team11/issue/repository/IssueRepository.java
  BE/server/src/main/java/com/team11/issue/repository/UserRepository.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/resources/application.properties
Labels: BE

#139 [BE] 예외처리 추가
  BE/server/src/main/java/com/team11/issue/config/JwtAuthInterceptor.java
  BE/server/src/main/java/com/team11/issue/exception/AssigneeIllegalException.java
  BE/server/src/main/java/com/team11/issue/exception/CommentNotFoundException.java
  BE/server/src/main/java/com/team11/issue/exception/GlobalExceptionHandler.java
  BE/server/src/main/java/com/team11/issue/exception/IssueNotFoundException.java
  BE/server/src/main/java/com/team11/issue/exception/JWTTokenException.java
  BE/server/src/main/java/com/team11/issue/exception/LabelNotFoundException.java
  BE/server/src/main/java/com/team11/issue/exception/MilestoneNotFoundException.java
  BE/server/src/main/java/com/team11/issue/exception/UserIllegalException.java
  BE/server/src/main/java/com/team11/issue/exception/UserNotFoundException.java
  BE/server/src/main/java/com/team11/issue/service/CommentService.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
  BE/server/src/main/java/com/team11/issue/service/LabelService.java
  BE/server/src/main/java/com/team11/issue/service/MilestoneService.java
  BE/server/src/main/java/com/team11/issue/service/UserService.java
  BE/server/src/main/java/com/team11/issue/util/JwtUtil.java
Labels: BE

#141 [BE] 이슈 목록 전체 조회에서 assignee와 comment 보이도록 수정
  BE/server/src/main/java/com/team11/issue/dto/issue/IssueResponseDTO.java
  BE/server/src/main/java/com/team11/issue/dto/issue/IssuesResponseDTO.java
  BE/server/src/main/java/com/team11/issue/service/IssueService.java
Labels: BE

#149 [FE] 이슈리스트 모달 기능 적용 및 이슈 작성 API 적용
  FE/src/components/Common/ListModal.tsx
  FE/src/components/Common/LoadingSpinner.tsx
  FE/src/components/Common/PrimaryButton.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/IssueList/InitFilterButton.tsx
  FE/src/components/IssueList/ListFilterModal.tsx
  FE/src/components/IssueList/ListTable/ListBody.tsx
  FE/src/components/IssueList/ListTable/ListHead.tsx
  FE/src/components/IssueList/NavFilter/SearchBar.tsx
  FE/src/components/IssueList/index.tsx
  FE/src/components/IssueWrite/WriteBody.tsx
  FE/src/components/IssueWrite/WriteFooter.tsx
  FE/src/components/IssueWrite/WriteHeader.tsx
  FE/src/components/IssueWrite/WriteOptionsModal.tsx
  FE/src/components/IssueWrite/index.tsx
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssueWritePage.tsx
  FE/src/pages/LoginCallBackPage.tsx
  FE/src/util/API.ts
  FE/src/util/hooks/index.ts
  FE/src/util/hooks/useCreateFilterItems.tsx
  FE/src/util/hooks/useFetch.tsx
  FE/src/util/hooks/useRefreshAPIDataState.tsx
  FE/src/util/hooks/useRefreshUserState.tsx
  FE/src/util/reference.ts
  FE/src/util/store/global.tsx
  FE/src/util/store/index.tsx
  FE/src/util/store/issueList.tsx
  FE/src/util/store/issueWrite.tsx
  FE/src/util/styles/theme/styled.d.ts
  FE/src/util/types/api.ts
  FE/src/util/types/index.ts
  FE/src/util/util.ts
  FE/src/util/util/const.ts
  FE/src/util/util/index.ts
  FE/src/util/util/issueList.ts
  FE/src/util/util/normal.ts
Labels: FE
